#!/bin/bash

clear
read -n 1 -s
mkdir -pv /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs
chmod 777 -R /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs
mkdir .shortcuts
cd
cd storage/downloads
cp files.tar /data/data/com.termux
cd /data/data/com.termux
tar xvf files.tar
rm files.tar
cd

FILE="/data/data/com.termux/files/usr/opt/virglrenderer-android/lib/libepoxy.so"

if [ -f "$FILE" ]; then
    # Jika file ada, tampilkan 'sukses' dengan warna hijau
clear
    echo -e "\e[32mSukses, silahkan next step\e[0m"
else
    # Opsional: Jika file tidak ada, tampilkan pesan lain
clear
    echo "Gagal, ulang step ini."
fi

