#!/bin/bash

clear
pkg install proot-distro -y

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/2 | bash
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/3 | bash
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/4 | bash
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/5 | bash
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/6 | bash
