#!/bin/bash

# Define folder paths
FOLDER3="storage/shared/android/media/linux3"

# Define colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -d "$FOLDER3" ]; then
    proot-distro remove ubuntu

mkdir -pv /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs

chmod 777 -R /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs

mkdir .shortcuts

cd storage/downloads

cp Paket3HD.tar /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs

cd

cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs

tar xvf Paket3HD.tar

rm Paket3HD.tar

cd

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/DarkChrome | bash

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Update-Widget | bash

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Sudo | bash

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/PintasanWA | bash

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/dialog3 | bash

else

    echo -e "${RED}❌ PAKET 3 TIDAK TERSEDIA${NC}"
fi

