#!/bin/bash

# Define folder paths
FOLDER3="storage/shared/android/media/linux3"

# Define colors
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -d "$FOLDER3" ]; then

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateHD3 | bash

else

    echo -e "${RED}❌ GAGAL, TABLET ANDA TERDETEKSI BARU ATAU BELUM PERNAH ORDER JASA SEBELUMNYA${NC}"
fi

