#!/bin/bash

clear
#!/bin/bash

# Definisi warna
HIJAU='\e[32m'
NORMAL='\e[0m'

echo -e "LINUX include WPS Office PC Level need activate, you can get product key from ${HIJAU}wpsarmlinux@gmail.com${NORMAL} or WhatsApp ${HIJAU}085865480245${NORMAL}"

echo " "