#!/bin/bash

clear
# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="DESKRIPSI INSTAL AUDACITY"
MENU="

Ini akan menginstal aplikasi AUDACITY.
Aplikasi editor untuk musik/suara.
Mungkin membutuhkan ruang sekitar 60mb."

# INI MENU AWAL
OPTIONS=(
1 "Lihat panduan penggunaan"
2 "Lanjut install Audacity"
3 "Batalkan")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
am start -a android.intent.action.VIEW -d https://wps-pclevel.blogspot.com/2025/02/panduan-setelah-install-libre-office.html?m=1
;;

2)
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Libre | bash
;;

2)
exit
;;

esac