#!/bin/bash

cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/etc/chromium.d

ls

rm README
rm apikeys
rm chromerefresh2023
rm dark_mode
rm enable_sync
rm extensions
rm performance_improvements
rm reduce_writes
rm site_dark_mode
