#!/bin/bash

clear
# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="MASUK LINUX DENGAN WIDGET"
MENU="

Ini akan mengganti metode masuk linux kalian.
Bebas ganti ke metode masuk linux tanpa widget
Silahkan baca metode penggunaan terlebih dahulu.
"

# INI MENU AWAL
OPTIONS=(
1 "Lihat contoh penggunaan"
2 "Lanjut install metode"
3 "Batal")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Gimpscape1 | bash
;;

2)
exit
;;

esac