#!/bin/bash

# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="LINUX DASHBOARD"
MENU="
Silahkan pilih menu"

# INI MENU AWAL
OPTIONS=(
1 "Matikan"
2 "Buka_Update"
3 "Terminal")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

 )
exit
;;

1)
pkill -f com.termux.x11
;;

2)
bash ~/.shortcuts/Buka_Update
exit
;;

3)
pkg j;;

esac
