#!/bin/bash

cd .shortcuts
ls
rm Buka_Update
rm Buka_Update1
rm Buka_Update2
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Buka_Update
chmod +x Buka_Update

cd

# INI MENU PILIHAN
HEIGHT=40
WIDTH=170
CHOICE_HEIGHT=5
TITLE="Pilih menu update"
MENU="Last update 23 Januari 2025. Jika dibuka tak ada apa², maka dalam proses."

# INI MENU AWAL
OPTIONS=(
1 "Link Tutorial"
2 "Tiktok Creator"
‎  ""
3 "Update Paket1 HD Version"
4 "Update Paket2 HD Version"
5 "Update Paket 3/4/5 HD Version"
‎  ""
6 "Update Kirim file .docx"
7 "Cara perbesar tampilan WPS & Linux"
‎  ""
8 "Install GIMP & Inkscape ( Alternative photoshop & corel )"
9 "Install WPS 365 ( bebas downgrade )"
10 "Install WPS 2019 ( bebas Upgrade )"
11 " ")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
am start -a android.intent.action.VIEW -d https://wps-pclevel.blogspot.com/p/update.html
exit 0
;;

2)
am start -a android.intent.action.VIEW -d https://tiktok.com/@rekberinnet
;;

3)
# Tentukan path ke file yang ingin dicek
file="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2/.local/share/mime/packages/Override.xml"

# Periksa keberadaan file
if [ -f "$file" ]; then
  # Jika file ada, tampilkan pesan "Ada"
  wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateHD1 | bash

else
  # Jika file tidak ada, tampilkan pesan "Tidak ada"
echo " "
echo -e  "Gagal :" "\033[31mTerdeteksi belum pernah instal Paket 1. 
Atau Terdeteksi perangkat baru.
Silahkan memakai jasa 085865480245 untuk menginstall Paket 1 linux terlebih dahulu.."
sleep 15
exit 0
fi
;;

4)
# Tentukan path ke file yang ingin dicek
file="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/etc/chromium.d/README"

# Periksa keberadaan file
if [ -f "$file" ]; then
  # Jika file ada, tampilkan pesan "Ada"
  wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateHD2 | bash

else
  # Jika file tidak ada, tampilkan pesan "Tidak ada"
echo " "
echo -e  "Gagal :" "\033[31mTerdeteksi belum pernah install Paket 2.
Atau terdeteksi perangkat baru.
Silahkan memakai jasa 085865480245 untuk menginstall Paket 2 linux terlebih dahulu.."

sleep 15
exit 0
fi
;;

6) 
echo dalam perbaikan
sleep 10
;;

7)
am start -a android.intent.action.VIEW -d https://wps-pclevel.blogspot.com/2025/01/cara-memperbesar-tampilan-jika-terlalu.html
;;

8)
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Gimpscape2 | bash
;;