#!/bin/bash

# Path ke file yang akan diperiksa
file1="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2/Notif1.txt"

# Periksa keberadaan file1
if [ -f "$file1" ]; then
    # Jika file ada, buat direktori lalu jalankan File-Update3
    mkdir -pv storage/shared/android/media/linux1
wget -O - https://cdn.jsdelivr.net/gh/panjiades/Update-3@main/File-Update3 | bash
else
    # Jika file tidak ada, jalankan File-Update2 (tanpa mkdir)
wget -O - https://cdn.jsdelivr.net/gh/panjiades/Update-3@main/File-Update2 | bash
fi


