#!/bin/bash


read -p "Masukkan password: " password

if [ "$password" = "InstallPaket2-888" ]; then
  wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateHD2-2 | bash
else
  echo "Password salah!"
fi

esac