#!bin/bash

proot-distro remove ubuntu

cd storage/downloads

mv Paket3HD.tar /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs


cd

cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs

tar xvf Paket3HD.tar

rm Paket3HD.tar


cd