#!bin/bash

proot-distro remove ubuntu

cd storage/downloads

mv Paket2HD.tar /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs


cd

cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs

tar xvf Paket2HD.tar

rm Paket2HD.tar


cd