#!/bin/bash

clear
# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="DESKRIPSI INSTAL LIBRE OFFICE"
MENU="

Ini akan menginstal aplikasi LIBRE OFFICE.
Ukuran sekitar 216 MB. 
Aplikasi ini berfungsi seperti WPS Office, namun bisa untuk edit file PDF secara langsung."

# INI MENU AWAL
OPTIONS=(
1 "Lanjut install Libre Office"
2 "Batalkan")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Libre | bash

am start -a android.intent.action.VIEW -d https://wps-pclevel.blogspot.com/2025/02/panduan-setelah-install-libre-office.html?m=1
;;

2)
exit
;;

esac