#!/bin/bash

# Tentukan URL yang ingin dibuka
URL="https://www.google.com"

# Kirim notifikasi dengan aksi default
# Aksi "default" harus dihandle oleh daemon notifikasi untuk membuat notifikasi dapat diklik.
notify-send \
  --action="default=Buka Google" \
  --expire-time=5000 \
  "Haii.." \
  "Selamat Datang Kembali paok" | while read -r line; do
    # Cek apakah aksi yang dikembalikan adalah "default"
    if [[ "$line" == "default" ]]; then
        # Jika diklik, buka URL menggunakan xdg-open
        xdg-open "$URL" &
        break
    fi
done
