#!/bin/bash

# Path ke file-file yang akan diperiksa
file1="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user/Desktop/wps-office-wps.desktop"
file2="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/etc/chromium.d/README"
file3="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2/code"

# Periksa keberadaan file1
if [ -f "$file1" ]; then
    mkdir -pv storage/shared/android/media/linux1
fi

# Periksa keberadaan file2
if [ -f "$file2" ]; then
    mkdir -pv storage/shared/android/media/linux2
fi

# Periksa keberadaan file3
if [ -f "$file3" ]; then
    mkdir -pv storage/shared/android/media/linux3
fi