#!/bin/bash

# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="WATERMAKS"
MENU="
Ii akan menghapus kalimat : 
Selamat datang kembali 🥰
Pastikan settingan linux beli di.. bla bla bla

Kalimat ini sebenarnya untuk menghargai creator. Namun kalian diperbolehkan untuk menghapusnya jika terasa mengganggu, tolong dipake dengan bijak ya 🙂‍↕️"

# INI MENU AWAL
OPTIONS=(
1 "Remove watermarks"
2 "Batal")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Notify | bash
;;

2)
exit
;;


esac