#!/bin/bash

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd Desktop; ln -s /storage/self/primary/Android/media/com.whatsapp.w4b/WhatsApp\ Business/Media/ WA\ Business; exit"


proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd Desktop; ln -s /storage/self/primary/Android/media/com.whatsapp/WhatsApp/Media/ WhatsApp; exit"

# Path ke file-file yang akan diperiksa
file1="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user/Desktop/WPS Writer.desktop"
file2="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/etc/chromium.d/README"
file3="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2/opt/android-studio/build.txt"

# Periksa keberadaan file1
if [ -f "$file1" ]; then
    mkdir -pv storage/shared/android/media/linux1
fi

# Periksa keberadaan file2
if [ -f "$file2" ]; then
    mkdir -pv storage/shared/android/media/linux2
fi

# Periksa keberadaan file3
if [ -f "$file3" ]; then
    mkdir -pv storage/shared/android/media/linux3
fi