#!/bin/bash

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd Desktop; ln -s /storage/self/primary/Android/media/com.whatsapp.w4b/WhatsApp\ Business/Media/ WA\ Business; exit"


proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd Desktop; ln -s /storage/self/primary/Android/media/com.whatsapp/WhatsApp/Media/ WhatsApp; exit"
