#!bin/bash

clear

echo -e "\033[37mMasukan password " "\033[32m123456" "\033[37m, lalu enter saja ( password tidak terlihat ) dan kemudian enter lagi"
echo " "

proot-distro login ubuntu -- bash -c "cd; apt remove sudo -y; apt install sudo -y;"

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; sudo apt update;"

clear

echo -e "\033[37mMasukan password " "\033[32m123456" "\033[37m, lalu enter saja ( password tidak terlihat ) dan kemudian enter lagi"
echo " "

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; sudo apt install pulseaudio pulseaudio-utils pavucontrol -y;"

sleep 3

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; sudo systemctl --user enable pulseaudio; sudo systemctl --user start pulseaudio;"

clear

echo "Sukses update Audio"

sleep 5

exit 0