#!/bin/bash

proot-distro login ubuntu --shared-tmp -- bash -c "cd; apt remove sudo -y; apt install sudo -y;"

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; a2dismod php8.3; a2dismod mpm_prefork; a2dismod mpm_worker; a2dismod mpm_event; service apache2 restart; a2enmod php8.3; service apache2 restart;"
clear


cd

cd ~/bin/




echo " "
echo "Sudo aktiv. Password default : 123456"
echo " "
GREEN='\033[0;32m'
GRAY_ITALIC='\033[3;90m'
NC='\033[0m' # No Color (Reset)

echo -e "${GREEN}✅ SUCCESS ✅ • Please close termux app and reopen it${NC}"
echo " "
echo -e "${GRAY_ITALIC}Press any key to exit${NC}"
