#!/bin/bash

# Path file yang ingin diperiksa
file_path="sd/Android/Media/tiny3"

# Memeriksa apakah file ada
if [ -f "$file_path" ]; then
    # Jika file ada, jalankan
    echo "File ditemukan. Menjalankan..."
    bash "$file_path"
else
clear

Gagal
sleep 5
exit

echo " "
cd sd/Android/Media
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/tiny3
cd
cd sd/Android/Media
bash tiny3

fi