#!/bin/bash

# Path file yang ingin diperiksa
file_path="sd/Android/Media/tiny3"

# Memeriksa apakah file ada
if [ -f "$file_path" ]; then
    # Jika file ada, jalankan
    echo "File ditemukan. Menjalankan..."
    bash "$file_path"
else
clear
echo " "
    # Jika file tidak ada, tampilkan pesan
    echo "link telah berubah. minta ke 085865480245 untuk link baru."
    echo "Harga 25K"
fi
