#!/bin/bash

cd

cd Desktop
ls
rm Internal; rm WA\ Business; rm WhatsApp

ln -s /sd Internal

ln -s /sd/Android/media/com.whatsapp.w4b/WhatsApp\ Business/Media/ WA\ Business

ln -s /sd/Android/media/com.whatsapp/WhatsApp/Media/ WhatsApp 

