#!/bin/bash

# Tentukan path ke file yang ingin dicek
file="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2/Desktop/Chromium Web Browser.desktop"

# Periksa keberadaan file
if [ -f "$file" ]; then
  # Jika file ada, tampilkan pesan "Ada"

proot-distro login ubuntu -- bash -c "cd; apt remove sudo -y; apt install sudo -y;"

clear

echo " "
echo -e "\033[37mMasukan password " "\033[32m123456" "\033[37m, lalu enter saja ( password tidak terlihat )"
echo " "
proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; sudo apt install chromium -y;"

clear

echo " "
echo "\033[32mSELESAI UPDATE CHROMIUM"
echo " "

else
  # Jika file tidak ada, tampilkan pesan "Tidak ada"
clear
echo " "
echo -e  "Gagal :" "\033[31mTerdeteksi belum pernah instal Chromium. 
Atau Terdeteksi perangkat baru.
Silahkan memakai jasa 085865480245 untuk menginstall Paket 2 linux terlebih dahulu.."
sleep 15
exit 0
fi