#!/bin/bash

clear
# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="DESKRIPSI INSTAL GIMP & INKSCAPE"
MENU="

Fix ini apabila kalian mengirim file dokumen .docx .xls atau dokumen WPS, melalui WhatsApp web di Firefox Linux dan setelah dikirim file-nya tidak bisa dibuka oleh teman kalian.

jika hal ini tidak dialami kak oleh kalian maka jangan dilakukan fix tidak apa-apa. 

"

# INI MENU AWAL
OPTIONS=(
1 "Lanjut fix"
2 "Batalkan")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
wget -O - https://raw.githubusercontent.com/panjiades/Update2/refs/heads/main/UpdateFixWAweb | bash
;;

2)
exit
;;

esac