#!/bin/bash


# Clear the screen
clear

#Deskripsi

echo " "
echo -e "\033[32mMENGENAI UPDATE WPS KE VERSI YANG LEBIH HD INI"
echo " "
echo " "
echo -e "\033[33mDeskripsi :"
echo -e "\033[37m

PAKET 1 ZOTERO"

echo " "
echo " "

# Fungsi untuk menampilkan hitung mundur horizontal
function countdown() {
    local seconds=$1
    for ((i=seconds; i>=0; i--)); do
        printf "\rCek file dalam : %ds" $i
        sleep 1
    done
    printf "\n"
}

# Panggil fungsi countdown dengan argumen 10 detik
countdown 10

# Tentukan path ke file yang ingin dicek
file="storage/downloads/Paket1HD.tar"

# Periksa keberadaan file
if [ -f "$file" ]; then
  # Jika file ada, tampilkan pesan "Ada"
  echo -e  "Cek file :" "\033[32mFile Update PAKET Sudah di download, melakukan otomatis install.."
else
  # Jika file tidak ada, tampilkan pesan "Tidak ada"
  echo -e "Cek File :" "\033[31mFile Update PAKET 1 Belum di download, Anda diarahkan otomatis ke halaman download.."
fi

sleep 10

echo  " "
echo " "

echo -e "\033[37m "
# INSTALASI ATAU DOWNLOAD LINK
file="storage/downloads/Paket1HD.tar"

# Periksa keberadaan file
if [ -f "$file" ]; then


pkill -f com.termux.x11

proot-distro remove ubuntu

mkdir -pv storage/shared/Linux\ Download\ Files
mkdir -pv storage/shared/WPS\ Backup

mkdir -pv "/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/halo"

chmod 777 -R "/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs"

mkdir ".shortcuts"

cd "storage/downloads"
ls

cp Paket1HD.tar "/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs"

cd
ls

cd "/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs"
ls

tar xvf Paket1HD.tar

rm Paket1HD.tar

cd
ls

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Sudo | bash

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/linux123 | bash

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Update-Widget | bash

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/dialog3 | bash

clear 
FILE_PATH="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/Notify.sh"

HIJAU='\033[0;32m'
MERAH='\033[0;31m'
NC='\033[0m' # No Color (Reset)

if [ -e "$FILE_PATH" ]; then
    echo -e "${HIJAU}Sukses install ✅${NC}"
echo "press any key.. to exit"
else
    echo -e "${MERAH}Gagal ❌ kemungkinan file Paket belum di folder downloads, atau file rusak. Ulangi langkah install lagi${NC}"
fi
read -n 1 -s
exit

else

clear

clear

echo "gagal, pastikan nama file Paket1HD.tar di folder download, atau download filenya dulu"


fi


exit 0