#!/bin/bash                              

ls
rm .bashrc
cd .shortcuts
ls
rm Mulai.sh
rm Matikan.sh
rm Buka
rm Buka.1
rm Buka.2
rm Tutup
rm Tutup.1
rm Tutup.2
rm Buka_Update
rm Buka_Update.1
rm Buka_Update.2
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Buka
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Tutup
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Buka_Update
chmod +x Buka
chmod +x Tutup
chmod +x Buka_Update
cd

cd /data/data/com.termux/files/usr/bin/
ls
rm off
rm on
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/on
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/off
chmod +x on
chmod +x off

cd

clear
echo -e "\033[0;32mBERHASIL DIPERBAHARUI"
echo -e "\033[1;33mSilahkan ketuk tombol kecil reload, di termux widget di beranda android kamu."
echo -e "\033[1;37m "
clear_and_print() {
  echo -ne "\rJendela ini akan keluar otomatis dalam $1 detik"
  sleep 1
}

# Loop untuk hitung mundur
for i in {30..1}; do
  clear_and_print "$i"
done
echo "Jendela ditutup!"
exit 0

