#!/bin/bash

# Tentukan path ke file yang ingin dicek
file="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/Notify.sh"

# Periksa keberadaan file
if [ -f "$file" ]; then
  # Jika file ada, tampilkan pesan "Ada"
  wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateBrave2 | bash

else
  # Jika file tidak ada, tampilkan pesan "Tidak ada"
echo " "
echo -e  "Gagal :" "\033[31mTerdeteksi belum pernah instal Brave Browser. 
Atau Terdeteksi perangkat baru.
Silahkan memakai jasa 085865480245 untuk menginstall Paket 2 linux terlebih dahulu.."
sleep 15
exit 0
fi
;;