#!/bin/bash

proot-distro login ubuntu -- bash -c "cd; sudo apt update; sudo apt install firefox-esr -y;"

clear

echo " "
echo -e "\033[32mSELESAI UPDATE"
echo -e "\033[37mSilahkan tutup linux, lalu buka lagi.."
echo " "
