#!/bin/bash

model=$(getprop ro.product.model)
if [ "$model" == "23117DRK48G" ]; then
  echo "Model perangkat terdeteksi: $model"
  echo "Menjalankan pkg update..."
  pkg update

elif [ "$model" == "2311DRK48G" ]; then
  clear
  echo "berhasil"

else

clear
  echo "Gagal. Hubungi Creator untuk install Custom"
fi
