#!/bin/bash

proot-distro login ubuntu -- bash -c "cd; sudo apt update;"

clear

echo " "
echo -e "\033[37mSilahkan ketik huruf" "\033[32mY" "\033[37mLalu ENTER"

proot-distro login ubuntu -- bash -c "cd; sudo apt install firefox-esr;"