#!/bin/bash

# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="DESKRIPSI UPDATE KE PAKET 3/4/5 HD"
MENU="

PAKET 3 ZOTERO"

# INI MENU AWAL
OPTIONS=(
1 "Download Bahan Update"
2 "Install"
3 "Batal")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
cd storage/downloads
ls
rm Paket3HD.tar
cd
am start -a android.intent.action.VIEW -d https://drive.usercontent.google.com/download?id=1ioE2DUFC9ICQlJaNVJ3fckJWnedKcRAC&export=download&authuser=0

wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateHD3-2 | bash
;;

2)
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateHD3 | bash
;;

3)
exit
;;

esac