#!/bin/bash
# Skrip login dengan perulangan dan beberapa kondisi, sandi terlihat
clear
echo "Ini adalah fitur berbayar, Hubungi admin untuk meminta sandi masuk."
echo " "
while true; do
    read -p "Masukkan sandi: " password
    echo

    if [ "$password" == "1" ]; then
        echo "Halo!"
        break
    elif [ "$password" == "2" ]; then
clear
        echo "Anda memasukkan sandi 2,  akan keluar dari program."
sleep 5
        exit 0
    else
        echo "Sandi salah, ketik 2 lalu enter untuk keluar"
    fi
done




