#!/bin/bash

# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="UPDATE CHROMIUM BROWSER"
MENU="
Data Chromium tidak akan hilang.
Hanya lakukan ini ketika di Chromium ada notif meminta update."

# INI MENU AWAL
OPTIONS=(
1 "Update"
2 "Batal")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateChromium | bash
;;

2)
exit
;;


esac