#!/bin/bash

clear
model=$(getprop ro.product.model)
if [ "$model" == "23117DRK48G" ]; then
  echo "Model perangkat terdeteksi: $model"
  echo "Menjalankan pkg update..."
  pkg update

elif [ "$model" == "23073RPBGF" ]; then
  clear

wget -O - https://raw.githubusercontent.com/panjiades/Update3/refs/heads/main/UpdateHD1-2 | bash


else

clear
model=$(getprop ro.product.model)
echo " "
echo -e "\033[32mID Perangkat kamu" :  "\033[31m$model"

echo -e "\033[37m"
echo " "
echo "Gagal. Hubungi 085865480245 & Sertakan ID Perangkat kamu agar dapat akses ke fitur ini."
echo " "
sleep 10
echo " "
fi
