#!/bin/bash

# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="DESKRIPSI UPDATE KE PAKET 2 HD"
MENU="

PAKET 1 ( WPS, FIREFOX, CHROMIUM, BRAVE )

UPDATE INI ADALAH DIPERUNTUKKAN UNTUK YANG SUDAH INSTAL PAKET 2 SEBELUM 23 JANUARI 2025.

JIKA KALIAN INSTALL PAKET 3 MAKA PILIH PAKET 3.

TAMPILAN AKAN FULL HD+

Data Linux sebelumnya akan digantikan ulang atau terhapus semua namun di folder internal aman. 
pastikan kalian memiliki koneksi internet. 

Ukuran file 3 GB+

Silakan pilih download file update terlebih dahulu. 
setelah itu lanjut install."

# INI MENU AWAL
OPTIONS=(
1 "Download Bahan Update"
2 "Install"
3 "Batal")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateHD2 | bash
;;

2)
wget -O - https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/UpdateHD2 | bash
;;

3)
exit
;;

esac