#!/bin/bash                              

cd .shortcuts
rm Mulai.sh
rm Matikan.sh
rm Buka.1
rm Buka.2
rm Tutup.1
rm Tutup.2
rm Update.1
rm Update.2
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Buka
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Tutup
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/Update
chmod +x Buka
chmod +x Tutup
chmod +x Update
cd

cd /data/data/com.termux/files/usr/bin/
ls
rm off
rm on
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/on
wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/off
chmod +x on
chmod +x off

cd

clear
echo -e "\033[0;32mBERHASIL DiPERBAHARUI"
echo -e "\033[1;37mSilahkan ketuk tombol kecil reload, di termux widget di beranda android kamu."
echo -e "\033[0;31m Tutup aja Apk Termux ini "


# Keluar dari terminal
exit
exit
