#!/bin/bash

clear
# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="DESKRIPSI INSTAL WPS 2019"
MENU="

Ini akan menginstall WPS 2019. WPS 365 akan hilang. Ukuran file 350mb+
Kalian bisa bebas suatu saat Downgrade ke WPS 2019.
Kalian Juga bebas Upgrade ke WPS 365 secara gratis.
"

# INI MENU AWAL
OPTIONS=(
1 "Lanjut install WPS 2019"
2 "Lihat review dahulu"
2 "Batalkan")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
wget -O - https://raw.githubusercontent.com/panjiades/Update2/refs/heads/main/DowngradeKeWPS2019 | bash
;;

2)
echo "Review sedang dibuat"
;;

3)
exit
;;

esac