#!/bin/bash

clear
# INI MENU PILIHAN
HEIGHT=30
WIDTH=80
CHOICE_HEIGHT=4
TITLE="FIX WAKTU KURANG SESUAI"
MENU="

Fix Jam kelebihan 1 jam atau kelambatan 2jam dll.
Ini akan mengubah Zona Jam, pada linux kalian.

TUTUP LINUX DULU
Lalu pilih zona kalian :
WIB ( Sumatra, Jawa, madura, Kalbar, Kalteng )
WITA ( Kaltim, Kalsel, Bali, NTB, NTT, Sulawesi )
WIT ( Maluku, Papua )"


# INI MENU AWAL
OPTIONS=(
1 "Set WIB"
2 "Set WITA"
3 "Set WIT"
4 "Set Brunei")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in

‎ )
exit
;;

1)
proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime;"

clear

echo " "

echo -e "\033[32mSelesai, sekarang buka linux kembali, klik di bagian jam. Jam akan menyesuaikan waktu tempat kalian."

echo -e "\033[37m "
;;

2)
proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; ln -sf /usr/share/zoneinfo/Asia/Makassar /etc/localtime;"

clear

echo " "

echo -e "\033[32mSelesai, sekarang buka linux kembali, klik di bagian jam. Jam akan menyesuaikan waktu tempat kalian."

echo -e "\033[37m "
;;

3)
proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; ln -sf /usr/share/zoneinfo/Asia/Jayapura /etc/localtime;"

clear

echo " "

echo -e "\033[32mSelesai, sekarang buka linux kembali, klik di bagian jam. Jam akan menyesuaikan waktu tempat kalian."
echo -e "\033[37m "
;;

4)
proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; ln -sf /usr/share/zoneinfo/Asia/Brunei /etc/localtime; date -s "yesterday"
";"

clear

echo " "

echo -e "\033[32mSelesai, sekarang buka linux kembali, klik di bagian jam. Jam akan menyesuaikan waktu tempat kalian."
echo -e "\033[37m "
;;

esac
