#!/bin/bash

# Tentukan path ke file yang ingin dicek
file="/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/etc/chromium.d/README"

# Periksa keberadaan file
if [ -f "$file" ]; then

cd /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/home/user2/Desktop/
ls
rm chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Profile_2.desktop

proot-distro login ubuntu --user user2 --shared-tmp -- bash -c "cd; cd Desktop; wget https://raw.githubusercontent.com/panjiades/Update-3/refs/heads/main/chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Profile_2.desktop; chmod 444 chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Profile_2.desktop"


 

echo "SUKSES PINTASAN WHATSAPP SUDAH AKTIV"

else
echo "Gagal, paket2 belum terinstal"
fi